### ISSUE TITLE
SCT methods for data augmentation

### ISSUE THREAD

**Issue by etdufay** [spinalcordtoolbox/detect-compression#3]
Hello, 

I wonder if there is any pre-built sct method that automatically performs data augmentation, such as mirroring, rotation, etc... 
It would be great to broaden my dataset. 

Thank you very much

**Comment by jcohenadad** [comment]
I don't think there is, but I highly recommend https://torchio.readthedocs.io/

**Comment by etdufay** [comment]
Alright thank you.
